### ISSUE TITLE
Unable to Build with Nginx 1.3.8 (windows 8, Visual Studio 10)

### ISSUE THREAD

**Issue by davidiusmaximus** [wandenberg/nginx-push-stream-module#57]
Hi.  I am not sure how much you support compiling on Windows but I wanted to run this by you.  I'm on Windows 8, 64-bit using Visual Studio 10.0.  Nginx compiles without a problem as long as I don't include your module.  If I do include the push_stream_module, it ends with the error pasted below.  I'm not great with C and compiler errors.  Was curious if you had any suggestions.  I've gotten it to compile in cygwin but nginx is acting funny in cygwin and I was hoping to avoid that extra layer.

Thanks for your help.

-david

```
    cl -c -O2  -W4 -WX -nologo -MT -Zi -DFD_SETSIZE=1024 -DNO_SYS_TYPES_H -Y
```

ungx_config.h -Fpobjs/ngx_config.pch -I src/core  -I src/event  -I src/event/mod
ules  -I src/os/win32  -I objs/exts/nginx-push-stream-module/src  -I objs/exts/n
ginx-push-stream-module/include  -I objs/lib/pcre-8.31  -I objs/lib/openssl-1.0.
1c/openssl/include  -I objs/lib/zlib-1.2.7  -I objs  -I src/http  -I src/http/mo
dules  -I src/mail  -Foobjs/addon/src/ngx_http_push_stream_module.obj  objs/exts
/nginx-push-stream-module/src/ngx_http_push_stream_module.c
ngx_http_push_stream_module.c
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(26) : error
 C2220: warning treated as error - no 'object' file generated
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(26) : warni
ng C4627: '#include <ngx_http_push_stream_module.h>': skipped when looking for p
recompiled header use
        Add directive to 'ngx_config.h' or rebuild precompiled header
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(27) : warni
ng C4627: '#include <ngx_http_push_stream_module_setup.c>': skipped when looking
 for precompiled header use
        Add directive to 'ngx_config.h' or rebuild precompiled header
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(28) : warni
ng C4627: '#include <ngx_http_push_stream_rbtree_util.c>': skipped when looking
for precompiled header use
        Add directive to 'ngx_config.h' or rebuild precompiled header
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(29) : warni
ng C4627: '#include <ngx_http_push_stream_module_utils.c>': skipped when looking
 for precompiled header use
        Add directive to 'ngx_config.h' or rebuild precompiled header
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(30) : warni
ng C4627: '#include <ngx_http_push_stream_module_ipc.c>': skipped when looking f
or precompiled header use
        Add directive to 'ngx_config.h' or rebuild precompiled header
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(31) : warni
ng C4627: '#include <ngx_http_push_stream_module_publisher.c>': skipped when loo
king for precompiled header use
        Add directive to 'ngx_config.h' or rebuild precompiled header
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(32) : warni
ng C4627: '#include <ngx_http_push_stream_module_subscriber.c>': skipped when lo
oking for precompiled header use
        Add directive to 'ngx_config.h' or rebuild precompiled header
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(33) : warni
ng C4627: '#include <ngx_http_push_stream_module_websocket.c>': skipped when loo
king for precompiled header use
        Add directive to 'ngx_config.h' or rebuild precompiled header
objs/exts/nginx-push-stream-module/src/ngx_http_push_stream_module.c(314) : fata
l error C1010: unexpected end of file while looking for precompiled header. Did
you forget to add '#include "ngx_config.h"' to your source?
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
